security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        in_memory:
            memory:
                users:
                    adwords:  { password: "%adwords_password%", roles: [ 'ROLE_ADWORDS' ] }

    firewalls:
        secured_area:
            pattern: ^/
            http_basic: ~
            anonymous: ~
            logout_on_user_change: true
