swiftmailer:
#    url: '%env(MAILER_URL)%'
#    spool: { type: 'memory' }
    default_mailer: mailer
    mailers:
        mailer:
            transport: "%mailer_transport%"
            host:      "%mailer_host%"
            port:      "%mailer_port%"
            username:  "%mailer_user%"
            password:  "%mailer_password%"
            spool:     { type: memory }
        mandrill:
            transport: "%mandrill_transport%"
            host:      "%mandrill_host%"
            port:      "%mandrill_port%"
            username:  "%mandrill_user%"
            password:  "%mandrill_password%"
            spool:     { type: memory }
