sudo: false
dist: trusty

language: php

env:
    global:
        - BUILD_CACHE_DIR=$HOME/.build-cache
        - TRAVIS_BUILD_DIR=.travis/build
        - APP_ENV=travis
        - APP_DEBUG=false

services:
  - mysql
  - memcached

php:
  - '7.2'

before_install:
  - .travis/before_install.sh

install:
  - .travis/install.sh

before_script:
  - .travis/before_script.sh

script:
  - .travis/script.sh

after_failure:
  - .travis/after_failure.sh

cache:
  directories:
    - $HOME/.composer/cache
    - vendor
    - $BUILD_CACHE_DIR
