intracto_gift_exchange:
    resource: "@IntractoGiftExchangeBundle/Resources/config/routing.yml"
    prefix:   /

intracto_secret_santa:
    resource: "@IntractoSecretSantaBundle/Resources/config/routing.yml"
    prefix:   /
