intracto.secretsanta.entry.index:
    path:     /entry/{url}
    defaults: { _controller: IntractoSecretSantaBundle:Entry:index }

intracto.secretsanta.entry.edit_email:
    path:     /entry/edit-email/{listUrl}/{entryId}
    defaults: { _controller: IntractoSecretSantaBundle:Entry:editEmail }

intracto.secretsanta.entry.dump_entries:
    path:     /dump-entries
    defaults: { _controller: IntractoSecretSantaBundle:Entry:dumpEntries }

intracto.secretsanta.entry.poke_buddy:
    path:     /poke/{url}/{entryId}
    defaults: { _controller: IntractoSecretSantaBundle:Entry:pokeBuddy }

intracto.secretsanta.entry.remove_entry_from_pool:
    path:     /entry/remove/{listUrl}/{entryId}
    defaults: { _controller: IntractoSecretSantaBundle:Entry:removeEntryFromPool }

intracto.secretsanta.static.privacypolicy:
    path:     /privacy-policy
    defaults: { _controller: IntractoSecretSantaBundle:Static:privacyPolicyAction }

intracto.secretsanta.static.faq:
    path:     /faq
    defaults: { _controller: IntractoSecretSantaBundle:Static:faqAction }