parameters:
    database_user: root
    database_password: ''
    geo_ip_db_path: /home/travis/.build-cache/GeoLite2-City.mmdb

services:
    swiftmailer.mailer.mailer: '@swiftmailer.mailer'
    swiftmailer.mailer.mandrill: '@swiftmailer.mailer'
