imports: ["behat.yml.dist"]

default:
    extensions:
        Behat\MinkExtension:
            base_url: 'http://localhost:8080/'

        Lakion\Behat\MinkDebugExtension:
            directory: .travis/build
            clean_start: false
            screenshot: true
